### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by marco-ahua** [lianglee/OhYesTheme#12]
Hi,

I set up your theme but it doesn't work, the white page and nothing. When i clik about upgrades.php here says it :

Fatal error: Class 'OhYesTheme' not found in /home/u532278058/public_html/elgg/mod/OhyesTheme/start.php on line 29

no acces at my admin nothing but i change the all document "ohyestheme" out in elgg ( in the new place ) i can use of new the admin.

Help me please

**Comment by sathish4fri** [comment]
Can you provide us you server details?

**Comment by JohnMuller** [comment]
Please provide us a your Elgg Error log.

**Comment by JohnMuller** [comment]
Try to remove a 'OhYesTheme' from 'mod' and then try to open your admin.

**Comment by marco-ahua** [comment]
elgg error is : Fatal error: Class 'OhYesTheme' not found in /home/u532278058/public_html/elgg/mod/OhyesTheme/start.php on line 29

Its good with other theme .

I remove "ohyesTheme' from 'mod' my admin work but when  i put the 'ohyestheme ' in 'mod' my admin doesn't work

**Comment by sathish4fri** [comment]
did use the latest version in github ??
if yes means we will check it use the before version 

because we need to check 
OhYesTheme::canCover()
if statement causing error

**Comment by JohnMuller** [comment]
Please send us your website link send your ftp details if you can to lianglee on community.elgg.org

**Comment by JohnMuller** [comment]
I am closing this issue due to no response
