### ISSUE TITLE
Intigrate hopscotch.js into ohyestheme  #enhancement

### ISSUE THREAD

**Issue by ghost** [lianglee/OhYesTheme#2]
few months back I started on Awsome theme Pro which will change the way of Elgging but as my collage started I gave that up but I will make my dream come true via this project

Search for hopscotch.js in github if you need help in implimenting it to the theme i would help you...

**Comment by lianglee** [comment]
I have transfered this 'future request' to one of our team member.
@sathish4fri

**Comment by sathish4fri** [comment]
sure i will try to do it

**Comment by sathish4fri** [comment]
@pranj7  tell me how can we achive that

**Comment by ghost** [comment]
@sathish4fri 
1) download hopscotch.js from Github
2)Place it in js folder of plugin
3)register the js
4)modify the hopscotch .js according to elgg HTML DIV id'd 
5) Done :)

**Comment by sathish4fri** [comment]
ok ...

**Comment by sathish4fri** [comment]
@lianglee  you want this hopscotch in our theme .... because it for setting tour ...........

**Comment by lianglee** [comment]
@sathish4fri i think the theme don't need hopscotch, i don't see any reasons to add into theme, what you say about it?

**Comment by seotraining1** [comment]
After some research into hopscotch i feel it is not appropriate for the ohyes theme though please add any more ideas you think could be implemented to the theme, i am going to close this ticket as a invalid"

**Comment by ghost** [comment]
I still keep my point as many of Elggers demanded it 
All sites like facebook and google+ have tours in it 
Rest is your choice
