### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by daveonche** [lianglee/OhYesTheme#20]
When a user's profile activities on the profile river reaches a certain amount, 40 or thereabout, that particular user's profile css stops to load. Even when other users try to view the profile, the css still does not load.

**Comment by sathish4fri** [comment]
we will check it . can you send the link of your site or post image of that so that we can verify it and clear it soon

**Comment by daveonche** [comment]
Am still testing on my desktop server before taking on my live site... Here is the error from the error log  "[Sat Aug 23 06:03:48.501659 2014] [:error] [pid 6768:tid 912] [client 127.0.0.1:62484] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\www.hypenia.com\\engine\\lib\\plugins.php on line 541, referer: http://127.0.0.1/www.hypenia.com/admin_dave?offset=20"

**Comment by daveonche** [comment]
![errorpage](https://cloud.githubusercontent.com/assets/3345961/4019737/ae7e2e9c-2a84-11e4-9cf5-e0daebc9bf13.png)

**Comment by lianglee** [comment]
Thank you for bug report

**Comment by lianglee** [comment]
I have investigated the issue, it seems something else causing this issue, try to disable other plugins,
and if problem still exists then reopen this issue
