### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by ghost** [lianglee/OhYesTheme#22]
Hi,

I need a french translation so I duplicate and translate the file en.php to fr.php

The ending line is set to 
add_translation("fr", $french);

But it doesn't work, what do i have to do to make it works ?

Thanks for your help.
Fred

**Comment by lianglee** [comment]
In Ossn 1.8 you need to edit libraries/ossn.lib.initialize.php find:

ossn_register_language('en', ossn_route()->locale . 'ossn.en.php');

Add new line below the line that i wrote above:
ossn_register_language('fr', ossn_route()->locale . 'ossn.fr.php');

**Comment by lianglee** [comment]
If its not working make sure your language is french in user settings.

**Comment by ghost** [comment]
French is set in users settings but sorry I don't understand what is Ossn

**Comment by ghost** [comment]
I cannot find a file like that in eggl nor in the theme

**Comment by lianglee** [comment]
I have deleted first comment i posted that by misunderstood. 

Ossn is : opensource-socialnetwork.org

**Comment by ghost** [comment]
Ok understood.

**Comment by ghost** [comment]
I didn't know that project, thansk to you mistake, I will test it ;-), and about my question ?

**Comment by lianglee** [comment]
Language should work, if its not working than there seems issue in language file post your language file on comuminity.elgg.org some one will reply you solution

**Comment by ghost** [comment]
Elgg is in french except the fews words of your theme for instance "unfriend", any idea ?

**Comment by lianglee** [comment]
Try this file: https://gist.github.com/lianglee/c3a88f55f2c80394e7be

**Comment by ghost** [comment]
I get it ! my file was wrong !! I didn't put the good variable name, It's ok know thanks for your help.

Here is my file for french translation of your theme :

$french = array(  
    'ohyes:home' => "Accueil",  
    'ohyes:photos' => 'Photos',
    'ohyes:blog' => 'Blog',
    'ohyes:bookmarks' => 'Signets',
    'ohyes:file' => 'Fichiers',
    'ohyes:pages' => 'Pages',
    'ohyes:messages' => 'Messages',
    'ohyes:groups' => 'Groupes',

```
'ohyes:admin:menu' => 'Administration',
'ohyes:add:friend' => 'Ajouter ami',
'ohyes:un:friend' => 'Enlever des amis',
'ohyes:message' => 'Message',
'ohyes:about' => 'A propos',
'profile:edit' => 'Editer',

'ohyes:cover:add' => 'Ajouter image de couverture',
'ohyes:theme:cover:done' => 'La couverture est ajoutée',
'ohyes:theme:cover:no' => "Impossible d'ajouter l'image de couverture",
'ohyes:theme:cover:removed' => "L'image de couverture a été enlevée",
'ohyes:theme:cover:remove:error' => "Impossible d'enlever l'image de couverture, réessayer",
```

 );

add_translation("fr", $french);

OSSN seems great, but when I changed language settings to german for instance, it still is in english. Is there some changes to do to over  library file ?

**Comment by ghost** [comment]
I get it ! Thanks for all !

**Comment by lianglee** [comment]
@Ossn v2.0 is under work there are alot of issue
