### ISSUE TITLE
on register page

### ISSUE THREAD

**Issue by sathish4fri** [lianglee/OhYesTheme#4]
from meril in elgg@community 
 can see you now developing a lot with your PHP skill. I want to remove the activity, blog, bookmark ... all this menu in the register field alone.. This is possible by using wall garden but wall garden will not allowe us to read blog, pages .. when not loged in.. is it possible to remove the header menu & still user able to read the blog ???

**Comment by ghost** [comment]
Yes it's possible @sathish4fri just make a index.php page which dont have header then done :)
see example of a index page here www.gleron.com

**Comment by sathish4fri** [comment]
@pranj7 i am asking @lianglee  there is any option there for removing header in the register page only ??
because we created it with the header in all the pages

**Comment by lianglee** [comment]
@sathish4fri , yes you can!/
 if(!elgg_in_context('register')){
   //header
 }

@sathish4fri  sorry , i have respond to this ticket late!
