### ISSUE TITLE
Add profile image cover

### ISSUE THREAD

**Issue by celu** [lianglee/OhYesTheme#6]
Type facebook and twitter

**Comment by lianglee** [comment]
@sathish4fri and @SZ1 what do you think? should we add or not?

**Comment by seotraining1** [comment]
anything that improves the theme sounds good to me i am working on getting some example codes for cover photos for mainly profile and pages not blogs as soon as i get these codes we can implement them to the ohyes theme!
 

---

FREE HOSTING WEBSITES SUB DOMAINS

http://s-z1.com/ 

http://sz1.eu/   

http://sfcircle.com/

szSocial the Knowledge Network

http://szsocial.com/

**Comment by sathish4fri** [comment]
yes we can improve it

**Comment by sathish4fri** [comment]
sorry my net is not working that why i am replying late

**Comment by lianglee** [comment]
added in 1.2

**Comment by celu** [comment]
thanks
